### PR TITLE
Pass public API to actions

### PR DESCRIPTION
**Pull request by Ramblurr**
This just brings with-create up to date with ember-power-select's api.

### CODE REVIEW

**Comment by Ramblurr** [comment]
@cibernox any chance we can get this merged?

**Comment by felixkiss** [comment]
This package depends on EPS `^0.10.1` (as far as the `package.json` is concerned).

I don't know it we can simply bump this to `^0.10.10` without breaking for people.

Was the public API also introduced @ `0.10.10`?

We could do this for a `1.0.0` release that uses EPS `^1.0.0` though.

**Comment by cibernox** [comment]
Wow, this has been here for ages. It looks reasonable to me. Merged

**Comment by Ramblurr** [comment]
Thanks @cibernox !

**Pull request merged**
