### PR TITLE
option to controle the position of ‘Add “${term}”…’ showCreatePosition

### PR DESCRIPTION
**Pull request by PratheepV**
#13

### CODE REVIEW

**Comment by PratheepV** [comment]
Any updates.....

**Comment by allancaffee** [comment]
I would find this option super helpful as well.

It might be good to include this option in the README and update the tests though.

**Comment by cibernox** [comment]
Sorry for the late delay. The PR seems perfect. Could you just add an integration test for this feature?

**Comment by PratheepV** [comment]
@cibernox  sure... I am working on it.

**Comment by PratheepV** [comment]
@cibernox Ping.

**Comment by cibernox** [comment]
Thanks! I'll release a new version now

**Comment by cibernox** [comment]
```
$ npm publish
+ ember-power-select-with-create@0.2.2
```

**Pull request merged**
