### PR TITLE
Add explicit component `power-select-multiple-with-create`

### LINKED ISSUE #35: doc for multiple select
The doc currently says to check the power select docs for options, but ember-power-select has a different helper for multiple selects, and does not pass an option. For power-select-with-create, you have to pass multiple=true - I found this out by searching through the issues on this repo. Can the doc please be updated? Also, are there any other options which aren't standard in power-select?

### PR DESCRIPTION
**Pull request by felixkiss**
Closes #35

This removes the option to pass `multiple=true` into the `power-select-with-create` component.

I wanted to try the [DRY template again](https://github.com/cibernox/ember-power-select-with-create/commit/ca437de791593dab0c2d14acecef08cdf6c65faa), [which has its problems](https://github.com/cibernox/ember-power-select-with-create/pull/33), because I think the duplication is a great source of possible bugs. The options passed into EPS were already out of sync (`oninput` was only passed in single selection mode, not in multiple selection mode).

@mdentremont Could you verify it is not rendering twice the same way you tested it in #32? I didn't quite get the hang of your steps to reproduce :)

But I think it shouldn't behave as it did in the past, because it doesn't use a computed property anymore, but rather a static string.

@cibernox Is this what you had in mind when talking about splitting this up into two components? Or is something missing?

### CODE REVIEW

**Comment by cibernox** [comment]
It's not what I had in mind but it's even better. I like that there is no duplication 👍 

Great work

**Comment by cibernox** [comment]
Released in 0.4.0! 🎉

**Comment by felixkiss** [comment]
Haha, a little fast with the merge 😄 
Hopefully there is no regression with double rendering, but what could possibly go wrong? ™️ 
😇

**Comment by cibernox** [comment]
@felixkiss That is what `X.X.1` versions are for 😄

**Pull request merged**
