### PR TITLE
Update to modern Octane and Glimmer

### PR DESCRIPTION
**Pull request by cah-briangantzler**
fixes https://github.com/cibernox/ember-power-select-with-create/issues/113

### CODE REVIEW

**Comment by cah-briangantzler** [comment]
I would like to drop ember 3.12 support and probably power select 3.   Updated the ember try scenarios and dont think it works
```
Build Error (TemplateCompiler)

EEXIST: file already exists, symlink '/var/folders/76/pygfd3k914100s1sf9x8xp2w0000gn/T/broccoli-5990VmdRvWU5yRfh/out-115-funnel_funnel_ember_power_select_with_create_addon/ember-power-select-with-create/components/power-select-with-create.js' -> '/var/folders/76/pygfd3k914100s1sf9x8xp2w0000gn/T/broccoli-5990VmdRvWU5yRfh/out-116-template_compiler/ember-power-select-with-create/components/power-select-with-create.js'


Stack Trace and Error Report: /var/folders/76/pygfd3k914100s1sf9x8xp2w0000gn/T/error.dump.98b8c7c2123971066108f923151e8e12.log

Result: false
---


------ RESULTS ------

Scenario ember-lts-3.12: FAIL
Command run: ember test
┌────────────────────┬────────────────────┬──────────────────────────────┬──────────┐
│ Dependency         │ Expected           │ Used                         │ Type     │
├────────────────────┼────────────────────┼──────────────────────────────┼──────────┤
│ ember-power-select │ ^3.0.0             │ 3.0.6                        │ yarn     │
├────────────────────┼────────────────────┼──────────────────────────────┼──────────┤
│ ember-source       │ ~3.12.0            │ 3.12.4                       │ yarn     │
└────────────────────┴────────────────────┴─────────────────────
```

**Comment by cibernox** [comment]
Totally, I'm cool with dropping such old stuff. We will only bump a minor version number when releasing

**Comment by cah-briangantzler** [comment]
Dropped 3.12 ember-try.  Removed the note that this was compatible with power-select 3, could add some ember tries if you wanted to keep that.

**Comment by cibernox** [comment]
Is this ready? Looks good to me.

**Comment by cah-briangantzler** [comment]
Yes, this is good.   

I may make a couple of changes for the need I have, will follow that up with some additional PRs if required.

**Comment by cibernox** [comment]
Merged! 🎉 

If you're planning on more changes I'll hold making a release. If you don't plan on making more, I can publish.

**Comment by cah-briangantzler** [comment]
I would publish. I an unsure if I need changes til I get to coding the other addon and since its a side project, I cant say when that will be

**Comment by cibernox** [comment]
Released in 0.9.0

**Pull request merged**
